FROM node:22-alpine AS api

WORKDIR /app

# Installation de pnpm globalement
RUN npm install -g pnpm

# Copie des fichiers de gestion de dépendances
COPY package.json pnpm-lock.yaml ./

# Installation des dépendances dev et prod
RUN pnpm install --frozen-lockfile

# Copie des autres fichiers (src, config, etc.)
COPY . .

# Copie de l'environnement (utile en dev si besoin d'un fichier spécifique)
COPY .env .env

# Expose le port, valeur par défaut si non spécifiée dans l'env
EXPOSE 5050

# Commande de lancement
CMD ["pnpm", "run", "start-dev"]
